import Head from "next/head";
import PizzaList from "../components/PizzaList";
import Slide from "../components/Slide";
import axios from "axios";

export default function Home({pizzaList}) {
  return (
    <div className="h-full w-full">
      <Head>
        <title>Pizza Restaurant || 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Slide />
      <PizzaList pizzaList={pizzaList} />
    </div>
  );
}

export const getServerSideProps = async (ctx) => {

  const res = await axios.get("http://localhost:3000/api/products");
  return {
    props: {
      pizzaList: res.data,
    },
  };
};

