import Head from "next/head";
import PizzaList from "../components/PizzaList";
import Slide from "../components/Slide";
import Footer from "./../components/Footer";
import Navbar from './../components/Navbar';

export default function Home() {
  return (
    <div className="m-0 p-0 overflow-hidden">
      <Head>
        <title>Pizza Restaurant || 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Slide />
      <PizzaList />
      <Footer />
    </div>
  );
}
